<?xml version="1.0" encoding="UTF-8"?>

<!--
    **Enunciado**
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
 <!ELEMENT declaraciones (consonante | tipo_de_dato | variable)>
 <!ELEMENT consonante (#PCDATA)>
 <!ATTLIST consonante valor CDATA #REQUIRED>
 <!ELEMENT tipo_de_dato (#PCDATA)>
 <!ELEMENT variable (#PCDATA)>
 <!ATTLIST variable tipo CDATA #REQUIRED>
]>
<declaraciones>
 <consonante valor="3.141592">PI</consonante>
 <variable tipo="real">radio</variable>
 <variable>area</variable>
 <variable>longitud</variable>
</declaraciones>
-->
<!DOCTYPE declaraciones [
 <!ELEMENT declaraciones (consonante | variable | tipo_de_dato)*>
 <!ELEMENT consonante (#PCDATA)>
    <!ATTLIST consonante valor CDATA #REQUIRED>
 <!ELEMENT variable (#PCDATA)>
    <!ATTLIST variable tipo CDATA #IMPLIED>
 <!ELEMENT tipo_de_dato (#PCDATA)>
]>
<declaraciones>
    <consonante valor="3.141592">PI</consonante>
    <variable tipo="real">radio</variable>
    <variable>area</variable>
    <variable>longitud</variable>
</declaraciones>