<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, apellidos, direccion, telefonos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT direccion (calle, numero, piso, cp, ciudad, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telefonos (telcasa+, telmovil*, teltrabajo*)>
<!ELEMENT telcasa (#PCDATA)>
<!ELEMENT telmovil (#PCDATA)>
<!ELEMENT teltrabajo (#PCDATA)>
]>
<agenda>
    <contacto>
        <nombre>Manuel</nombre>
        <apellidos>Gomez Gomez</apellidos>
        <direccion>
            <calle>Geranio</calle>
            <numero>4</numero>
            <piso>1A</piso>
            <cp>21001</cp>
            <ciudad>Huelva</ciudad>
            <provincia>Huelva</provincia>
        </direccion>
        <telefonos>
            <telcasa>959100100</telcasa>
            <telmovil>600100100</telmovil>
            <teltrabajo>959200200</teltrabajo>
        </telefonos>
    </contacto>
</agenda>